SELECT E.FIRST_NAME
  || E.LAST_NAME NAME,
  D.DEPARTMENT_ID,
  E.SALARY E.EMPLOYEE_ID A,
  D.DEPARTMENT_NAME B,
  E.EMAIL M,
  E.SALARY "SELECT",
  5 Z,
  (SELECT 2 COL_1 FROM DUAL
  ) F
FROM EMPLOYEES E
JOIN DEPARTMENTS D
ON (D.DEPARTMENT_ID    =E.DEPARTMENT_ID)
WHERE E.DEPARTMENT_ID IN
  (SELECT D.DEPARTMENT_ID FROM DEPARTMENTS
  );
